name: Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org

      - name: Temporarily fix corepack bug
        run: npm install -g corepack@latest

      - name: Setup pnpm
        run: |-
          corepack enable
          pnpm --version

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >>$GITHUB_OUTPUT

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14

      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm run build:wasm

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          file: tree-sitter-fish.wasm
          tag: ${{ github.ref }}

      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_KEY }}
